#### MANUP SEANCE 2

In [11]:
import pandas as pd

In [12]:
#lire dataFrame avec pandas
df = pd.read_excel(r"C:\Users\simo\Downloads\Etudiants.xlsx") #r: rowString

In [13]:
df

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
11,CD000012,SAMI ILIASS,08/10/1995,NADOR,16.01,SCIENCES PHYSIQUES,NaN,NaN,4.0
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
14,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
15,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
16,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
17,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
18,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
19,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0

In [14]:
#print(df)

In [15]:
df.head(10) #Les 10 premieres lignes par defaut c est 5

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0

In [16]:
# Les 8 derniers
df.tail(8)

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
14,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
15,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
16,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
17,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
18,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
19,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0

In [17]:
df.shape #la forme nbr de ligne et de colonne 
# c est un tuple cad on ne peut modifier les valeurs

(20, 9)

In [18]:
type(df.shape)

tuple

In [19]:
#afficher seulement le nbr de premier element du tuple
df.shape[0]

20

In [20]:
df.shape[1]

9

In [21]:
df.iloc[0:8]
#retourner un nbr de valeur

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0

In [22]:
# Fetch rows from for 4 to 6
df.iloc[3:6]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0

In [23]:
df.iloc[6:9] #7 to 9 etudiant

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0

In [24]:
df.iloc[0]

CIN                                  CD000001
Nom et Prenom                   BOUZIDI AMINE
Date de Naissance                  09/03/2000
Lieu de Naissance                         FES
Note Bac                                14.29
Option Bac           sciences mathématiques a
Note Licence                            14.07
Option Licence                            SMI
Nombre Années                             3.0
Name: 0, dtype: object

In [25]:
df.iloc[0].values

array(['CD000001', 'BOUZIDI AMINE', '09/03/2000', 'FES',
       np.float64(14.29), 'sciences mathématiques a', np.float64(14.07),
       'SMI', np.float64(3.0)], dtype=object)

In [26]:
df.iloc[0].values[0]

'CD000001'

In [27]:
df.iloc[0].values[7]

'SMI'

In [28]:
type(df['Date de Naissance'])

pandas.core.series.Series

In [29]:
df['Date de Naissance']

0     09/03/2000
1      2003-12-8
2      1994-6-28
3     25/11/2002
4     19/10/2003
5       8/8/1999
6      2004-1-23
7     01/01/2001
8     28/02/2002
9      1998-5-16
10     29/2/1992
11    08/10/1995
12           NaN
13    25/11/2002
14     2003-12-8
15    28/02/2002
16     2004-1-23
17     1994-6-28
18      8/8/1999
19    01/01/2001
Name: Date de Naissance, dtype: object

In [30]:
type(df['Date de Naissance'].values)

numpy.ndarray

In [31]:
df['Date de Naissance'].values

array(['09/03/2000', '2003-12-8', '1994-6-28', '25/11/2002', '19/10/2003',
       '8/8/1999', '2004-1-23', '01/01/2001', '28/02/2002', '1998-5-16',
       '29/2/1992', '08/10/1995', nan, '25/11/2002', '2003-12-8',
       '28/02/2002', '2004-1-23', '1994-6-28', '8/8/1999', '01/01/2001'],
      dtype=object)

In [32]:
# date de naissance 5iem etudiant
df['Date de Naissance'].values[4]

'19/10/2003'

In [33]:
#Les noms des colonnes
df.columns

Index(['CIN', 'Nom et Prenom', 'Date de Naissance', 'Lieu de Naissance',
       'Note Bac', 'Option Bac', 'Note Licence', 'Option Licence',
       'Nombre Années'],
      dtype='object')

In [34]:
df.columns[0]

'CIN'

In [35]:
df[df.columns[0]].values #equivaut a ecrire df["CIN"]

array(['CD000001', 'CD000002', 'CD000003', 'CD000004', 'CD000005',
       'CD000006', 'CD000007', 'CD000008', 'CD000009', 'CD000010',
       'CD000011', 'CD000012', 'CD000013', 'CD000004', 'CD000002',
       'CD000009', 'CD000007', 'CD000003', 'CD000006', 'CD000008'],
      dtype=object)

In [36]:
df["Nom et Prenom"].values

array(['BOUZIDI AMINE', 'ALAMI ALAE', 'ZANOUU ABDERAHIMME',
       'BENSLIMANE ILHAME', 'AMMI KARIM', 'SAIQ MOHAMMED', 'OUATIK JALAL',
       'ZAIM MERIAM', 'CHIBI HIBA', 'DMINI SAAD', 'AOUADI HAMZA',
       'SAMI ILIASS', 'ALAOUI ANASS', 'BENSLIMANE ILHAME', 'ALAMI ALAE',
       'CHIBI HIBA', 'OUATIK JALAL', 'ZANOUU ABDERAHIMME',
       'SAIQ MOHAMMED', 'ZAIM MERIAM'], dtype=object)

In [43]:
df[["CIN", "Nom et Prenom"]].values[0][0]

'CD000001'

In [44]:
df[["CIN", "Nom et Prenom", "Date de Naissance"]].iloc[5:8]

        CIN  Nom et Prenom Date de Naissance
5  CD000006  SAIQ MOHAMMED          8/8/1999
6  CD000007   OUATIK JALAL         2004-1-23
7  CD000008    ZAIM MERIAM        01/01/2001

### FILTRER

In [45]:
#
df["Nombre Années"]

0     3.0
1     3.0
2     5.0
3     6.0
4     3.0
5     5.0
6     4.0
7     3.0
8     3.0
9     5.0
10    NaN
11    4.0
12    NaN
13    6.0
14    3.0
15    3.0
16    4.0
17    5.0
18    5.0
19    3.0
Name: Nombre Années, dtype: float64

In [46]:
df["Nombre Années"] > 5

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13     True
14    False
15    False
16    False
17    False
18    False
19    False
Name: Nombre Années, dtype: bool

In [47]:
df[df["Nombre Années"]>5]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
13,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0

In [48]:
df[df["Nombre Années"]>= 4]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0
11,CD000012,SAMI ILIASS,08/10/1995,NADOR,16.01,SCIENCES PHYSIQUES,NaN,NaN,4.0
13,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
16,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
17,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
18,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0

In [49]:
df[df["Note Licence"]>= 14] #CEUX qui ont une note licence plus de 14

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
14,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
15,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
18,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
19,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0

In [50]:
df[df["Note Licence"]>= 15]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
14,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
15,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
18,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0

In [51]:
df[df["Note Licence"]>= 15][["Nom et Prenom","Note Licence"]]

    Nom et Prenom  Note Licence
1      ALAMI ALAE         15.31
4      AMMI KARIM         15.94
5   SAIQ MOHAMMED         16.09
8      CHIBI HIBA         15.23
14     ALAMI ALAE         15.31
15     CHIBI HIBA         15.23
18  SAIQ MOHAMMED         16.09

In [52]:
df[df["Note Licence"]>= 15][["Nom et Prenom","Note Licence"]].values[0][1]

15.31

In [53]:
df[df["Note Licence"]>= 15][["Nom et Prenom","Note Licence"]].values

array([['ALAMI ALAE', 15.31],
       ['AMMI KARIM', 15.94],
       ['SAIQ MOHAMMED', 16.09],
       ['CHIBI HIBA', 15.23],
       ['ALAMI ALAE', 15.31],
       ['CHIBI HIBA', 15.23],
       ['SAIQ MOHAMMED', 16.09]], dtype=object)

In [54]:
df[(df["Lieu de Naissance"] == "FES") |( df["Lieu de Naissance"] == "RABAT")]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
14,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
16,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
17,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
19,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0

In [55]:
df[(df["Lieu de Naissance"] == "FES") & ( df["Option Licence"] == "SMC")]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.0,SMC,4.0
16,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.0,SMC,4.0

In [56]:
df[df["Lieu de Naissance"].isin(["FES","RABAT"])]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
14,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
16,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
17,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
19,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0

# TRAIETEMENT

In [57]:
#description sur les donnees de notre dataframe
df.describe()

        Note Bac  Note Licence  Nombre Années
count  18.000000     17.000000      18.000000
mean   14.040556     13.920588       4.055556
std     2.819504      1.979831       1.109967
min    10.520000     10.000000       3.000000
25%    11.010000     12.520000       3.000000
50%    14.070000     14.870000       4.000000
75%    16.332500     15.310000       5.000000
max    18.170000     16.090000       6.000000

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CIN                20 non-null     object
 1   Nom et Prenom      20 non-null     object
 2   Date de Naissance  19 non-null     object
 3   Lieu de Naissance  19 non-null     object
 4   Note Bac           18 non-null     float64
 5   Option Bac         18 non-null     object
 6   Note Licence       17 non-null     float64
 7   Option Licence     18 non-null     object
 8   Nombre Années      18 non-null     float64
dtypes: float64(3), object(6)
memory usage: 1.5+ KB

In [59]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13     True
14     True
15     True
16     True
17     True
18     True
19     True
dtype: bool

In [60]:
df[df["Nom et Prenom"].duplicated()]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
13,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
14,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
15,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
16,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
17,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
18,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
19,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0

In [61]:
# remove duplicate
df.drop_duplicates()

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
11,CD000012,SAMI ILIASS,08/10/1995,NADOR,16.01,SCIENCES PHYSIQUES,NaN,NaN,4.0
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
df

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
11,CD000012,SAMI ILIASS,08/10/1995,NADOR,16.01,SCIENCES PHYSIQUES,NaN,NaN,4.0
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
14,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
15,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
16,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
17,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
18,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
19,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0

In [63]:
#df= df.drop_duplicates()
df.drop_duplicates(inplace = True)

In [64]:
df

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
11,CD000012,SAMI ILIASS,08/10/1995,NADOR,16.01,SCIENCES PHYSIQUES,NaN,NaN,4.0
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Traiter les valeurs nuls

In [65]:
df["Note Licence"].isna()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
12     True
Name: Note Licence, dtype: bool

In [66]:
df[df["Note Licence"].isna()]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
11,CD000012,SAMI ILIASS,08/10/1995,NADOR,16.01,SCIENCES PHYSIQUES,NaN,NaN,4.0
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
df[df["Note Licence"].isna() | df["Option Licence"].isna()]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
11,CD000012,SAMI ILIASS,08/10/1995,NADOR,16.01,SCIENCES PHYSIQUES,NaN,NaN,4.0
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
df[df["Note Bac"].isna() & df["Option Licence"].isna()]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
df.isna()

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,True,True,True,False,True
11,False,False,False,False,False,False,True,True,False
12,False,False,True,True,True,True,True,True,True

In [70]:
df.isna().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
12     True
dtype: bool

In [71]:
# decipts rows with a null value
df[df.isna().any(axis=1)] #axis for line

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
11,CD000012,SAMI ILIASS,08/10/1995,NADOR,16.01,SCIENCES PHYSIQUES,NaN,NaN,4.0
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
# decipts columns with a null value
df.isna().any(axis=0)

CIN                  False
Nom et Prenom        False
Date de Naissance     True
Lieu de Naissance     True
Note Bac              True
Option Bac            True
Note Licence          True
Option Licence        True
Nombre Années         True
dtype: bool

In [73]:
#seleon les colonnes
df.isna().sum(axis=1)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    4
11    2
12    7
dtype: int64

In [74]:
#seleon les colonnes
df.isna().sum()

CIN                  0
Nom et Prenom        0
Date de Naissance    1
Lieu de Naissance    1
Note Bac             2
Option Bac           2
Note Licence         3
Option Licence       2
Nombre Années        2
dtype: int64

# PREPROCESSING

In [75]:
#MODIF NON PERMENANT POUR AFFICHAGE ET REMPLACER LES NULLS PAR AUCUNE
df.fillna('AUCUNE')

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.0,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.0,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0
10,CD000011,AOUADI HAMZA,29/2/1992,FES,AUCUNE,AUCUNE,AUCUNE,Sciences Mathématiques et Informatique,AUCUNE
11,CD000012,SAMI ILIASS,08/10/1995,NADOR,16.01,SCIENCES PHYSIQUES,AUCUNE,AUCUNE,4.0
12,CD000013,ALAOUI ANASS,AUCUNE,AUCUNE,AUCUNE,AUCUNE,AUCUNE,AUCUNE,AUCUNE

In [76]:
#pour supprimer les nulls
#df.fillna('AUCUNE', inplace=True)
#df = df.fillna('AUCUNE')

In [77]:
df

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
11,CD000012,SAMI ILIASS,08/10/1995,NADOR,16.01,SCIENCES PHYSIQUES,NaN,NaN,4.0
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
# removing rows that contain null values

df.dropna(inplace=True)

##or
##df = df.dropna()

In [79]:
df

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0

In [80]:
"ALAOUI  AHMED ".split(" ")[0]

'ALAOUI'

In [83]:
"ALAOUI AHMED ".split(" ")[1]

'AHMED'

In [108]:
nom=[]
prenom=[]
for i in (df["Nom et Prenom"].values):
    nom.append(i.split(' ')[0])
    prenom.append(i.split(' ')[1])
    print(i.split(' ')[0])
    print(i.split(' ')[1])
    print("*"*10)
print(nom)
print(prenom)
#df[["Nom","Prenom"]] = df["Nom et Prenom"].str.split(' ',n=1, expand=True)

BOUZIDI
AMINE
**********
ALAMI
ALAE
**********
ZANOUU
ABDERAHIMME
**********
BENSLIMANE
ILHAME
**********
AMMI
KARIM
**********
SAIQ
MOHAMMED
**********
OUATIK
JALAL
**********
ZAIM
MERIAM
**********
CHIBI
HIBA
**********
DMINI
SAAD
**********
['BOUZIDI', 'ALAMI', 'ZANOUU', 'BENSLIMANE', 'AMMI', 'SAIQ', 'OUATIK', 'ZAIM', 'CHIBI', 'DMINI']
['AMINE', 'ALAE', 'ABDERAHIMME', 'ILHAME', 'KARIM', 'MOHAMMED', 'JALAL', 'MERIAM', 'HIBA', 'SAAD']

In [111]:
df.insert(1, 'Nom', nom) 
df.insert(2, 'Prenom', prenom)

In [112]:
df

,CIN,Nom,Prenom,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI,AMINE,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI,ALAE,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU,ABDERAHIMME,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE,ILHAME,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI,KARIM,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ,MOHAMMED,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK,JALAL,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM,MERIAM,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI,HIBA,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI,SAAD,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0

In [113]:
df.drop('Nom', axis=1,inplace=True)
df.drop('Prenom', axis=1, inplace=True)

In [114]:
df

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0

In [115]:
df[["Nom","Prenom"]] = df["Nom et Prenom"].str.split(' ',n=1, expand=True)

In [117]:
df

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années,Nom,Prenom
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0,BOUZIDI,AMINE
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0,ALAMI,ALAE
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0,ZANOUU,ABDERAHIMME
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0,BENSLIMANE,ILHAME
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0,AMMI,KARIM
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0,SAIQ,MOHAMMED
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0,OUATIK,JALAL
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0,ZAIM,MERIAM
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0,CHIBI,HIBA
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0,DMINI,SAAD

In [118]:
df.columns

Index(['CIN', 'Nom et Prenom', 'Date de Naissance', 'Lieu de Naissance',
       'Note Bac', 'Option Bac', 'Note Licence', 'Option Licence',
       'Nombre Années', 'Nom', 'Prenom'],
      dtype='object')

In [130]:
#suppression de Nom et prenom
#df = df.drop("Nom et Prenom", axis=1)

In [140]:
#Unifier la forme de la date 
df["Date de Naissance"]= pd.to_datetime(df["Date de Naissance"], format='mixed')

In [141]:
df

,CIN,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années,Nom,Prenom
0,CD000001,2000-03-09,FES,14.29,sciences mathématiques a,14.07,SMI,3.0,BOUZIDI,AMINE
1,CD000002,2003-08-12,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0,ALAMI,ALAE
2,CD000003,1994-06-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0,ZANOUU,ABDERAHIMME
3,CD000004,2002-11-25,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0,BENSLIMANE,ILHAME
4,CD000005,2003-10-19,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0,AMMI,KARIM
5,CD000006,1999-08-08,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0,SAIQ,MOHAMMED
6,CD000007,2004-01-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0,OUATIK,JALAL
7,CD000008,2001-01-01,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0,ZAIM,MERIAM
8,CD000009,2002-02-28,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0,CHIBI,HIBA
9,CD000010,1998-05-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0,DMINI,SAAD

In [142]:
#dt = “je veux utiliser des fonctions de date”
df["Date de Naissance"]= df["Date de Naissance"].dt.strftime('%d/%m/%Y')

In [143]:
df

,CIN,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années,Nom,Prenom
0,CD000001,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0,BOUZIDI,AMINE
1,CD000002,12/08/2003,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0,ALAMI,ALAE
2,CD000003,28/06/1994,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0,ZANOUU,ABDERAHIMME
3,CD000004,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0,BENSLIMANE,ILHAME
4,CD000005,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0,AMMI,KARIM
5,CD000006,08/08/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0,SAIQ,MOHAMMED
6,CD000007,23/01/2004,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0,OUATIK,JALAL
7,CD000008,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0,ZAIM,MERIAM
8,CD000009,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0,CHIBI,HIBA
9,CD000010,16/05/1998,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0,DMINI,SAAD

In [ ]:
--t-,im,;

In [144]:
df.columns

Index(['CIN', 'Date de Naissance', 'Lieu de Naissance', 'Note Bac',
       'Option Bac', 'Note Licence', 'Option Licence', 'Nombre Années', 'Nom',
       'Prenom'],
      dtype='object')

In [145]:
df["Option Bac"]

0             sciences mathématiques a
1             sciences mathématiques b
2                   SCIENCES PHYSIQUES
3                   SCIENCES PHYSIQUES
4    sciences de la vie et de la terre
5             SCIENCES MATHÉMATIQUES B
6             SCIENCES MATHÉMATIQUES B
7    SCIENCES DE LA VIE ET DE LA TERRE
8                   sciences physiques
9             SCIENCES MATHÉMATIQUES A
Name: Option Bac, dtype: object

In [149]:
df["Option Bac"]=df["Option Bac"].str.upper()

In [150]:
df

,CIN,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années,Nom,Prenom
0,CD000001,09/03/2000,FES,14.29,SCIENCES MATHÉMATIQUES A,14.07,SMI,3.0,BOUZIDI,AMINE
1,CD000002,12/08/2003,RABAT,10.52,SCIENCES MATHÉMATIQUES B,15.31,Sciences Mathématiques et Applications,3.0,ALAMI,ALAE
2,CD000003,28/06/1994,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0,ZANOUU,ABDERAHIMME
3,CD000004,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0,BENSLIMANE,ILHAME
4,CD000005,19/10/2003,DAKHLA,13.85,SCIENCES DE LA VIE ET DE LA TERRE,15.94,SVI,3.0,AMMI,KARIM
5,CD000006,08/08/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0,SAIQ,MOHAMMED
6,CD000007,23/01/2004,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0,OUATIK,JALAL
7,CD000008,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0,ZAIM,MERIAM
8,CD000009,28/02/2002,MEKNES,15.73,SCIENCES PHYSIQUES,15.23,Sciences de la Matière Physique,3.0,CHIBI,HIBA
9,CD000010,16/05/1998,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0,DMINI,SAAD

In [151]:
df["Option Licence"]

0                                       SMI
1    Sciences Mathématiques et Applications
2                                       SMP
3             Sciences de la Matière Chimie
4                                       SVI
5                                       SMA
6                                       SMC
7                        Sciences de la Vie
8           Sciences de la Matière Physique
9    Sciences Mathématiques et Informatique
Name: Option Licence, dtype: object

In [169]:
df=df[[df.columns[0],df.columns[8],df.columns[9],df.columns[1],df.columns[2],df.columns[3],df.columns[4],df.columns[5],df.columns[6],df.columns[7]]]

In [172]:
df

,CIN,Option Bac,Note Licence,Option Licence,Nombre Années,Nom,Prenom,Date de Naissance,Lieu de Naissance,Note Bac
0,CD000001,SCIENCES MATHÉMATIQUES A,14.07,SMI,3.0,BOUZIDI,AMINE,09/03/2000,FES,14.29
1,CD000002,SCIENCES MATHÉMATIQUES B,15.31,Sciences Mathématiques et Applications,3.0,ALAMI,ALAE,12/08/2003,RABAT,10.52
2,CD000003,SCIENCES PHYSIQUES,12.52,SMP,5.0,ZANOUU,ABDERAHIMME,28/06/1994,FES,11.01
3,CD000004,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0,BENSLIMANE,ILHAME,25/11/2002,TANGER,18.17
4,CD000005,SCIENCES DE LA VIE ET DE LA TERRE,15.94,SVI,3.0,AMMI,KARIM,19/10/2003,DAKHLA,13.85
5,CD000006,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0,SAIQ,MOHAMMED,08/08/1999,MEKNES,17.00
6,CD000007,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0,OUATIK,JALAL,23/01/2004,FES,10.68
7,CD000008,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0,ZAIM,MERIAM,01/01/2001,RABAT,12.96
8,CD000009,SCIENCES PHYSIQUES,15.23,Sciences de la Matière Physique,3.0,CHIBI,HIBA,28/02/2002,MEKNES,15.73
9,CD000010,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0,DMINI,SAAD,16/05/1998,FES,16.44

In [180]:
mapping={
    "SCIENCES PHYSIQUES":"SMP",
    "SCIENCES DE LA VIE ET DE LA TERRE":"SVT",
    "SCIENCES MATHÉMATIQUES A ":"SM A",
    "SCIENCES MATHÉMATIQUES B":"SM B"
}

In [188]:
mapping={
    "Sciences Mathématiques et Applications":"SMA",
    "Sciences de la Matière Chimie":"SMC",
    "Sciences de la Vie":"SVI",
    "Sciences de la Matière Physique":"SMP",
    "Sciences Mathématiques et Informatique":"SMI"
}

In [189]:
df["Option Licence"]=df["Option Licence"].replace(mapping)

In [190]:
df

,CIN,Option Bac,Note Licence,Option Licence,Nombre Années,Nom,Prenom,Date de Naissance,Lieu de Naissance,Note Bac
0,CD000001,SCIENCES MATHÉMATIQUES A,14.07,SMI,3.0,BOUZIDI,AMINE,09/03/2000,FES,14.29
1,CD000002,SCIENCES MATHÉMATIQUES B,15.31,SMA,3.0,ALAMI,ALAE,12/08/2003,RABAT,10.52
2,CD000003,SCIENCES PHYSIQUES,12.52,SMP,5.0,ZANOUU,ABDERAHIMME,28/06/1994,FES,11.01
3,CD000004,SCIENCES PHYSIQUES,13.46,SMC,6.0,BENSLIMANE,ILHAME,25/11/2002,TANGER,18.17
4,CD000005,SCIENCES DE LA VIE ET DE LA TERRE,15.94,SVI,3.0,AMMI,KARIM,19/10/2003,DAKHLA,13.85
5,CD000006,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0,SAIQ,MOHAMMED,08/08/1999,MEKNES,17.00
6,CD000007,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0,OUATIK,JALAL,23/01/2004,FES,10.68
7,CD000008,SCIENCES DE LA VIE ET DE LA TERRE,14.87,SVI,3.0,ZAIM,MERIAM,01/01/2001,RABAT,12.96
8,CD000009,SCIENCES PHYSIQUES,15.23,SMP,3.0,CHIBI,HIBA,28/02/2002,MEKNES,15.73
9,CD000010,SCIENCES MATHÉMATIQUES A,11.68,SMI,5.0,DMINI,SAAD,16/05/1998,FES,16.44

In [191]:
df.to_excel(r'C:\Users\simo\Desktop\MASTER\PBI\Etudiants_clean.xlsx', index=False)

In [193]:
df.to_csv(r'C:\Users\simo\Desktop\MASTER\PBI\Etudiants_clean.csv', index=False)

In [196]:
df.to_csv(r'C:\Users\simo\Desktop\MASTER\PBI\Etudiants_clean_cvs2', index=False)

In [179]:
df.groupby(["Option Bac"])["CIN"].count()

Option Bac
 SCIENCES PHYSIQUES                  3
SCIENCES DE LA VIE ET DE LA TERRE    2
SCIENCES MATHÉMATIQUES A             2
SCIENCES MATHÉMATIQUES B             3
Name: CIN, dtype: int64

In [195]:
#df.groupby(["Lieu de Naissance"]).aggragate(

In [194]:
#df.drop()