In [2]:
import pandas as pd
from datetime import datetime

1.	Charger le fichier "MLAIM.csv" en utilisant pandas.read_csv.

In [13]:
df = pd.read_csv(r"C:\Users\hp\Desktop\MASTER_1\S2\PBI_other\PBI\MLAIM.csv")

In [14]:
df

     N            Nom            Prenom Date_Naissance Ville_Naissance
0    1   AIT EL FATMI           YOUSSEF     09/03/2000             FES
1    2          AJJAL            ISMAIL     2003-12-08           RABAT
2    3          AMILA            AYMANE    28-Jun-1994             FES
3    4         AZOUGH             YAHYA     11/25/2002          TANGER
4    5            BAH      MAMADOU OURY     10.19.2003          DAKHLA
5    6          BAYAD             OTMAN       08/08/99          MEKNES
6    7        BOUSBAA             KENZA     23/01/2004             FES
7    8          BRIKA             SALMA     01-01-2001           RABAT
8    9        CHIAHNI          MAROUANE     28.02.2002          MEKNES
9   10      DELICIEUX             CALEB    16 May 1998             FES
10  11         ECHIBI             RAJAE     29/02/1992             FES
11  12      EL BASSRI           YASSINE     1995-10-08           NADOR
12  13     EL BISSARI             IMANE            NaN             FES
13  14   EL BOURAKADI           KHADIJA       25/11/02          TANGER
14  15      EL FELLAK             HAJAR    08 Dec 2003           RABAT
15  16       EL HADRI               AYA       28-02-02          MEKNES
16  17     EL HANSALI            HAFSSA       23/01/04             FES
17  18     EL MOQADEM   AYMANE MOUBARIK    Jun 28 1994             FES
18  19  EL MOUHADDANA           YASSINE     08/08/1999          MEKNES
19  20   EL-MAKHLOUFI          MOHAMMED     01/01/2001           RABAT
20  21   EL-MAKHLOUFY      SALAH-EDDINE            NaN          TANGER
21  22     ET-TAALABI           SEFIANE     29/02/1992           RABAT
22  23       EZZARIBA           KHADIJA            NaN          MEKNES
23  24        GUARTET         ABDESSLAM     28/06/1994             FES
24  25         HANIDA           CHAYMAE            NaN             FES
25  26        JAAFARI         NASRELLAH       08/08/99          MEKNES
26  27         MAACHI          ABDELLAH     25/11/2002          TANGER
27  28        MELIANI          ROMAISSA     09/03/2000             FES
28  29         MEYABA      MOHAMED VALL     08/12/2003           RABAT
29  30           MIME              SAAD     28/06/1994             FES
30  31         NDIAYE  MOUHAMED NAZIROU       25/11/02          TANGER
31  32          N'MAR             HAJAR     10.19.2003          DAKHLA
32  33      OUHCHOUCH           ZAKARIA      08-Aug-99          MEKNES
33  34        QATAOUI               AYA       23-01-04             FES
34  35       RAJOUANI            FAYSAL     01/01/2001           RABAT
35  36          RAKTA           NISRINE     28.02.2002          MEKNES
36  37          ZAHIR          MOHAMMED    16 May 1998             FES
37  31         NDIAYE  MOUHAMED NAZIROU       25/11/02          TANGER
38  32          N'MAR             HAJAR     10.19.2003          DAKHLA
39  33      OUHCHOUCH           ZAKARIA      08-Aug-99          MEKNES
40  26        JAAFARI         NASRELLAH       08/08/99          MEKNES
41  27         MAACHI          ABDELLAH     25/11/2002          TANGER
42  28        MELIANI          ROMAISSA     09/03/2000             FES
43  29         MEYABA      MOHAMED VALL     08/12/2003           RABAT

In [15]:
#print(df)

In [16]:
df.head(10)

    N           Nom        Prenom Date_Naissance Ville_Naissance
0   1  AIT EL FATMI       YOUSSEF     09/03/2000             FES
1   2         AJJAL        ISMAIL     2003-12-08           RABAT
2   3         AMILA        AYMANE    28-Jun-1994             FES
3   4        AZOUGH         YAHYA     11/25/2002          TANGER
4   5           BAH  MAMADOU OURY     10.19.2003          DAKHLA
5   6         BAYAD         OTMAN       08/08/99          MEKNES
6   7       BOUSBAA         KENZA     23/01/2004             FES
7   8         BRIKA         SALMA     01-01-2001           RABAT
8   9       CHIAHNI      MAROUANE     28.02.2002          MEKNES
9  10     DELICIEUX         CALEB    16 May 1998             FES

2.	Supprimer les lignes qui contiennent des valeurs vides.

In [23]:
df.describe()

               N
count  44.000000
mean   20.659091
std    10.674776
min     1.000000
25%    11.750000
50%    22.500000
75%    29.250000
max    37.000000

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   N                44 non-null     int64
 1   Nom              44 non-null     object
 2   Prenom           44 non-null     object
 3   Date_Naissance   40 non-null     object
 4   Ville_Naissance  44 non-null     object
dtypes: int64(1), object(4)
memory usage: 1.8+ KB

In [26]:
df.isna()

        N    Nom  Prenom  Date_Naissance  Ville_Naissance
0   False  False   False           False            False
1   False  False   False           False            False
2   False  False   False           False            False
3   False  False   False           False            False
4   False  False   False           False            False
5   False  False   False           False            False
6   False  False   False           False            False
7   False  False   False           False            False
8   False  False   False           False            False
9   False  False   False           False            False
10  False  False   False           False            False
11  False  False   False           False            False
12  False  False   False            True            False
13  False  False   False           False            False
14  False  False   False           False            False
15  False  False   False           False            False
16  False  False   False           False            False
17  False  False   False           False            False
18  False  False   False           False            False
19  False  False   False           False            False
20  False  False   False            True            False
21  False  False   False           False            False
22  False  False   False            True            False
23  False  False   False           False            False
24  False  False   False            True            False
25  False  False   False           False            False
26  False  False   False           False            False
27  False  False   False           False            False
28  False  False   False           False            False
29  False  False   False           False            False
30  False  False   False           False            False
31  False  False   False           False            False
32  False  False   False           False            False
33  False  False   False           False            False
34  False  False   False           False            False
35  False  False   False           False            False
36  False  False   False           False            False
37  False  False   False           False            False
38  False  False   False           False            False
39  False  False   False           False            False
40  False  False   False           False            False
41  False  False   False           False            False
42  False  False   False           False            False
43  False  False   False           False            False

In [43]:
#“Est-ce qu’il y a AU MOINS une valeur manquante dans chaque colonne ?”
df.isna().any(axis=0)
#df.isna().any(axis=1)

N                  False
Nom                False
Prenom             False
Date_Naissance      True
Ville_Naissance    False
dtype: bool

In [54]:
#Est-ce qu’il y a AU MOINS une valeur manquante dans chaque ligne ?
df.isna().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
21    False
22     True
23    False
24     True
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
dtype: bool

In [55]:
#le nombre valeur manquant pour chaque colonne
df.isna().sum()

N                  0
Nom                0
Prenom             0
Date_Naissance     4
Ville_Naissance    0
dtype: int64

In [56]:
#df.loc[ lignes , colonnes ]
df.loc[:,df.isna().any(axis=0)]

#Le ~ = NOT (inverse True ↔ False)

   Date_Naissance
0      09/03/2000
1      2003-12-08
2     28-Jun-1994
3      11/25/2002
4      10.19.2003
5        08/08/99
6      23/01/2004
7      01-01-2001
8      28.02.2002
9     16 May 1998
10     29/02/1992
11     1995-10-08
12            NaN
13       25/11/02
14    08 Dec 2003
15       28-02-02
16       23/01/04
17    Jun 28 1994
18     08/08/1999
19     01/01/2001
20            NaN
21     29/02/1992
22            NaN
23     28/06/1994
24            NaN
25       08/08/99
26     25/11/2002
27     09/03/2000
28     08/12/2003
29     28/06/1994
30       25/11/02
31     10.19.2003
32      08-Aug-99
33       23-01-04
34     01/01/2001
35     28.02.2002
36    16 May 1998
37       25/11/02
38     10.19.2003
39      08-Aug-99
40       08/08/99
41     25/11/2002
42     09/03/2000
43     08/12/2003

In [57]:
df.fillna('AUCUNE')

     N            Nom            Prenom Date_Naissance Ville_Naissance
0    1   AIT EL FATMI           YOUSSEF     09/03/2000             FES
1    2          AJJAL            ISMAIL     2003-12-08           RABAT
2    3          AMILA            AYMANE    28-Jun-1994             FES
3    4         AZOUGH             YAHYA     11/25/2002          TANGER
4    5            BAH      MAMADOU OURY     10.19.2003          DAKHLA
5    6          BAYAD             OTMAN       08/08/99          MEKNES
6    7        BOUSBAA             KENZA     23/01/2004             FES
7    8          BRIKA             SALMA     01-01-2001           RABAT
8    9        CHIAHNI          MAROUANE     28.02.2002          MEKNES
9   10      DELICIEUX             CALEB    16 May 1998             FES
10  11         ECHIBI             RAJAE     29/02/1992             FES
11  12      EL BASSRI           YASSINE     1995-10-08           NADOR
12  13     EL BISSARI             IMANE         AUCUNE             FES
13  14   EL BOURAKADI           KHADIJA       25/11/02          TANGER
14  15      EL FELLAK             HAJAR    08 Dec 2003           RABAT
15  16       EL HADRI               AYA       28-02-02          MEKNES
16  17     EL HANSALI            HAFSSA       23/01/04             FES
17  18     EL MOQADEM   AYMANE MOUBARIK    Jun 28 1994             FES
18  19  EL MOUHADDANA           YASSINE     08/08/1999          MEKNES
19  20   EL-MAKHLOUFI          MOHAMMED     01/01/2001           RABAT
20  21   EL-MAKHLOUFY      SALAH-EDDINE         AUCUNE          TANGER
21  22     ET-TAALABI           SEFIANE     29/02/1992           RABAT
22  23       EZZARIBA           KHADIJA         AUCUNE          MEKNES
23  24        GUARTET         ABDESSLAM     28/06/1994             FES
24  25         HANIDA           CHAYMAE         AUCUNE             FES
25  26        JAAFARI         NASRELLAH       08/08/99          MEKNES
26  27         MAACHI          ABDELLAH     25/11/2002          TANGER
27  28        MELIANI          ROMAISSA     09/03/2000             FES
28  29         MEYABA      MOHAMED VALL     08/12/2003           RABAT
29  30           MIME              SAAD     28/06/1994             FES
30  31         NDIAYE  MOUHAMED NAZIROU       25/11/02          TANGER
31  32          N'MAR             HAJAR     10.19.2003          DAKHLA
32  33      OUHCHOUCH           ZAKARIA      08-Aug-99          MEKNES
33  34        QATAOUI               AYA       23-01-04             FES
34  35       RAJOUANI            FAYSAL     01/01/2001           RABAT
35  36          RAKTA           NISRINE     28.02.2002          MEKNES
36  37          ZAHIR          MOHAMMED    16 May 1998             FES
37  31         NDIAYE  MOUHAMED NAZIROU       25/11/02          TANGER
38  32          N'MAR             HAJAR     10.19.2003          DAKHLA
39  33      OUHCHOUCH           ZAKARIA      08-Aug-99          MEKNES
40  26        JAAFARI         NASRELLAH       08/08/99          MEKNES
41  27         MAACHI          ABDELLAH     25/11/2002          TANGER
42  28        MELIANI          ROMAISSA     09/03/2000             FES
43  29         MEYABA      MOHAMED VALL     08/12/2003           RABAT

In [58]:
df.dropna(inplace=True)

In [59]:
df

     N            Nom            Prenom Date_Naissance Ville_Naissance
0    1   AIT EL FATMI           YOUSSEF     09/03/2000             FES
1    2          AJJAL            ISMAIL     2003-12-08           RABAT
2    3          AMILA            AYMANE    28-Jun-1994             FES
3    4         AZOUGH             YAHYA     11/25/2002          TANGER
4    5            BAH      MAMADOU OURY     10.19.2003          DAKHLA
5    6          BAYAD             OTMAN       08/08/99          MEKNES
6    7        BOUSBAA             KENZA     23/01/2004             FES
7    8          BRIKA             SALMA     01-01-2001           RABAT
8    9        CHIAHNI          MAROUANE     28.02.2002          MEKNES
9   10      DELICIEUX             CALEB    16 May 1998             FES
10  11         ECHIBI             RAJAE     29/02/1992             FES
11  12      EL BASSRI           YASSINE     1995-10-08           NADOR
13  14   EL BOURAKADI           KHADIJA       25/11/02          TANGER
14  15      EL FELLAK             HAJAR    08 Dec 2003           RABAT
15  16       EL HADRI               AYA       28-02-02          MEKNES
16  17     EL HANSALI            HAFSSA       23/01/04             FES
17  18     EL MOQADEM   AYMANE MOUBARIK    Jun 28 1994             FES
18  19  EL MOUHADDANA           YASSINE     08/08/1999          MEKNES
19  20   EL-MAKHLOUFI          MOHAMMED     01/01/2001           RABAT
21  22     ET-TAALABI           SEFIANE     29/02/1992           RABAT
23  24        GUARTET         ABDESSLAM     28/06/1994             FES
25  26        JAAFARI         NASRELLAH       08/08/99          MEKNES
26  27         MAACHI          ABDELLAH     25/11/2002          TANGER
27  28        MELIANI          ROMAISSA     09/03/2000             FES
28  29         MEYABA      MOHAMED VALL     08/12/2003           RABAT
29  30           MIME              SAAD     28/06/1994             FES
30  31         NDIAYE  MOUHAMED NAZIROU       25/11/02          TANGER
31  32          N'MAR             HAJAR     10.19.2003          DAKHLA
32  33      OUHCHOUCH           ZAKARIA      08-Aug-99          MEKNES
33  34        QATAOUI               AYA       23-01-04             FES
34  35       RAJOUANI            FAYSAL     01/01/2001           RABAT
35  36          RAKTA           NISRINE     28.02.2002          MEKNES
36  37          ZAHIR          MOHAMMED    16 May 1998             FES
37  31         NDIAYE  MOUHAMED NAZIROU       25/11/02          TANGER
38  32          N'MAR             HAJAR     10.19.2003          DAKHLA
39  33      OUHCHOUCH           ZAKARIA      08-Aug-99          MEKNES
40  26        JAAFARI         NASRELLAH       08/08/99          MEKNES
41  27         MAACHI          ABDELLAH     25/11/2002          TANGER
42  28        MELIANI          ROMAISSA     09/03/2000             FES
43  29         MEYABA      MOHAMED VALL     08/12/2003           RABAT

In [61]:
df.isna().sum()

N                  0
Nom                0
Prenom             0
Date_Naissance     0
Ville_Naissance    0
dtype: int64

In [65]:
df.isna().any(axis=0) #pour les colonnes

N                  False
Nom                False
Prenom             False
Date_Naissance     False
Ville_Naissance    False
dtype: bool

3.	Supprimer les lignes en doublons.

In [74]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
21    False
23    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37     True
38     True
39     True
40     True
41     True
42     True
43     True
dtype: bool

In [76]:
df[df.duplicated()]

     N        Nom            Prenom Date_Naissance Ville_Naissance
37  31     NDIAYE  MOUHAMED NAZIROU       25/11/02          TANGER
38  32      N'MAR             HAJAR     10.19.2003          DAKHLA
39  33  OUHCHOUCH           ZAKARIA      08-Aug-99          MEKNES
40  26    JAAFARI         NASRELLAH       08/08/99          MEKNES
41  27     MAACHI          ABDELLAH     25/11/2002          TANGER
42  28    MELIANI          ROMAISSA     09/03/2000             FES
43  29     MEYABA      MOHAMED VALL     08/12/2003           RABAT

In [82]:
df.drop_duplicates(inplace=True)

In [83]:
df

     N            Nom            Prenom Date_Naissance Ville_Naissance
0    1   AIT EL FATMI           YOUSSEF     09/03/2000             FES
1    2          AJJAL            ISMAIL     2003-12-08           RABAT
2    3          AMILA            AYMANE    28-Jun-1994             FES
3    4         AZOUGH             YAHYA     11/25/2002          TANGER
4    5            BAH      MAMADOU OURY     10.19.2003          DAKHLA
5    6          BAYAD             OTMAN       08/08/99          MEKNES
6    7        BOUSBAA             KENZA     23/01/2004             FES
7    8          BRIKA             SALMA     01-01-2001           RABAT
8    9        CHIAHNI          MAROUANE     28.02.2002          MEKNES
9   10      DELICIEUX             CALEB    16 May 1998             FES
10  11         ECHIBI             RAJAE     29/02/1992             FES
11  12      EL BASSRI           YASSINE     1995-10-08           NADOR
13  14   EL BOURAKADI           KHADIJA       25/11/02          TANGER
14  15      EL FELLAK             HAJAR    08 Dec 2003           RABAT
15  16       EL HADRI               AYA       28-02-02          MEKNES
16  17     EL HANSALI            HAFSSA       23/01/04             FES
17  18     EL MOQADEM   AYMANE MOUBARIK    Jun 28 1994             FES
18  19  EL MOUHADDANA           YASSINE     08/08/1999          MEKNES
19  20   EL-MAKHLOUFI          MOHAMMED     01/01/2001           RABAT
21  22     ET-TAALABI           SEFIANE     29/02/1992           RABAT
23  24        GUARTET         ABDESSLAM     28/06/1994             FES
25  26        JAAFARI         NASRELLAH       08/08/99          MEKNES
26  27         MAACHI          ABDELLAH     25/11/2002          TANGER
27  28        MELIANI          ROMAISSA     09/03/2000             FES
28  29         MEYABA      MOHAMED VALL     08/12/2003           RABAT
29  30           MIME              SAAD     28/06/1994             FES
30  31         NDIAYE  MOUHAMED NAZIROU       25/11/02          TANGER
31  32          N'MAR             HAJAR     10.19.2003          DAKHLA
32  33      OUHCHOUCH           ZAKARIA      08-Aug-99          MEKNES
33  34        QATAOUI               AYA       23-01-04             FES
34  35       RAJOUANI            FAYSAL     01/01/2001           RABAT
35  36          RAKTA           NISRINE     28.02.2002          MEKNES
36  37          ZAHIR          MOHAMMED    16 May 1998             FES

4.	Unifier la forme des dates de la colonne "Date_Naissance".

In [99]:
df["Date_Naissance"]=pd.to_datetime(df["Date_Naissance"], format='mixed')

In [100]:
df["Date_Naissance"]

0    2000-03-09
1    2003-08-12
2    1994-06-28
3    2002-11-25
4    2003-10-19
5    1999-08-08
6    2004-01-23
7    2001-01-01
8    2002-02-28
9    1998-05-16
10   1992-02-29
11   1995-08-10
13   2002-11-25
14   2003-08-12
15   2002-02-28
16   2004-01-23
17   1994-06-28
18   1999-08-08
19   2001-01-01
21   1992-02-29
23   1994-06-28
25   1999-08-08
26   2002-11-25
27   2000-03-09
28   2003-12-08
29   1994-06-28
30   2002-11-25
31   2003-10-19
32   1999-08-08
33   2004-01-23
34   2001-01-01
35   2002-02-28
36   1998-05-16
Name: Date_Naissance, dtype: datetime64[ns]

In [101]:
df["Date_Naissance"]=df["Date_Naissance"].dt.strftime('%d/%m/%Y')

In [102]:
df

     N            Nom            Prenom Date_Naissance Ville_Naissance
0    1   AIT EL FATMI           YOUSSEF     09/03/2000             FES
1    2          AJJAL            ISMAIL     12/08/2003           RABAT
2    3          AMILA            AYMANE     28/06/1994             FES
3    4         AZOUGH             YAHYA     25/11/2002          TANGER
4    5            BAH      MAMADOU OURY     19/10/2003          DAKHLA
5    6          BAYAD             OTMAN     08/08/1999          MEKNES
6    7        BOUSBAA             KENZA     23/01/2004             FES
7    8          BRIKA             SALMA     01/01/2001           RABAT
8    9        CHIAHNI          MAROUANE     28/02/2002          MEKNES
9   10      DELICIEUX             CALEB     16/05/1998             FES
10  11         ECHIBI             RAJAE     29/02/1992             FES
11  12      EL BASSRI           YASSINE     10/08/1995           NADOR
13  14   EL BOURAKADI           KHADIJA     25/11/2002          TANGER
14  15      EL FELLAK             HAJAR     12/08/2003           RABAT
15  16       EL HADRI               AYA     28/02/2002          MEKNES
16  17     EL HANSALI            HAFSSA     23/01/2004             FES
17  18     EL MOQADEM   AYMANE MOUBARIK     28/06/1994             FES
18  19  EL MOUHADDANA           YASSINE     08/08/1999          MEKNES
19  20   EL-MAKHLOUFI          MOHAMMED     01/01/2001           RABAT
21  22     ET-TAALABI           SEFIANE     29/02/1992           RABAT
23  24        GUARTET         ABDESSLAM     28/06/1994             FES
25  26        JAAFARI         NASRELLAH     08/08/1999          MEKNES
26  27         MAACHI          ABDELLAH     25/11/2002          TANGER
27  28        MELIANI          ROMAISSA     09/03/2000             FES
28  29         MEYABA      MOHAMED VALL     08/12/2003           RABAT
29  30           MIME              SAAD     28/06/1994             FES
30  31         NDIAYE  MOUHAMED NAZIROU     25/11/2002          TANGER
31  32          N'MAR             HAJAR     19/10/2003          DAKHLA
32  33      OUHCHOUCH           ZAKARIA     08/08/1999          MEKNES
33  34        QATAOUI               AYA     23/01/2004             FES
34  35       RAJOUANI            FAYSAL     01/01/2001           RABAT
35  36          RAKTA           NISRINE     28/02/2002          MEKNES
36  37          ZAHIR          MOHAMMED     16/05/1998             FES

5.	Ajouter une nouvelle colonne nommée "Age" qui calcule l'âge des étudiants en se basant sur leurs dates de naissance "Date_Naissance".

DataFrame.insert(loc, column, value, allow_duplicates=False)

In [117]:
#df.insert(,,)
print(datetime.now())

2026-03-31 03:21:38.259477

 df["age"] = (pd.to_datetime("today") - df["date_naissance"]).dt.days // 365

In [125]:
today= datetime.today()
df["Date_Naissance"]= pd.to_datetime(df['Date_Naissance'], format='mixed')

#print(today)
df["age"]= today.year - df['Date_Naissance'].dt.year

In [130]:
df

     N            Nom            Prenom Date_Naissance Ville_Naissance  age
0    1   AIT EL FATMI           YOUSSEF     2000-09-03             FES   26
1    2          AJJAL            ISMAIL     2003-12-08           RABAT   23
2    3          AMILA            AYMANE     1994-06-28             FES   32
3    4         AZOUGH             YAHYA     2002-11-25          TANGER   24
4    5            BAH      MAMADOU OURY     2003-10-19          DAKHLA   23
5    6          BAYAD             OTMAN     1999-08-08          MEKNES   27
6    7        BOUSBAA             KENZA     2004-01-23             FES   22
7    8          BRIKA             SALMA     2001-01-01           RABAT   25
8    9        CHIAHNI          MAROUANE     2002-02-28          MEKNES   24
9   10      DELICIEUX             CALEB     1998-05-16             FES   28
10  11         ECHIBI             RAJAE     1992-02-29             FES   34
11  12      EL BASSRI           YASSINE     1995-10-08           NADOR   31
13  14   EL BOURAKADI           KHADIJA     2002-11-25          TANGER   24
14  15      EL FELLAK             HAJAR     2003-12-08           RABAT   23
15  16       EL HADRI               AYA     2002-02-28          MEKNES   24
16  17     EL HANSALI            HAFSSA     2004-01-23             FES   22
17  18     EL MOQADEM   AYMANE MOUBARIK     1994-06-28             FES   32
18  19  EL MOUHADDANA           YASSINE     1999-08-08          MEKNES   27
19  20   EL-MAKHLOUFI          MOHAMMED     2001-01-01           RABAT   25
21  22     ET-TAALABI           SEFIANE     1992-02-29           RABAT   34
23  24        GUARTET         ABDESSLAM     1994-06-28             FES   32
25  26        JAAFARI         NASRELLAH     1999-08-08          MEKNES   27
26  27         MAACHI          ABDELLAH     2002-11-25          TANGER   24
27  28        MELIANI          ROMAISSA     2000-09-03             FES   26
28  29         MEYABA      MOHAMED VALL     2003-08-12           RABAT   23
29  30           MIME              SAAD     1994-06-28             FES   32
30  31         NDIAYE  MOUHAMED NAZIROU     2002-11-25          TANGER   24
31  32          N'MAR             HAJAR     2003-10-19          DAKHLA   23
32  33      OUHCHOUCH           ZAKARIA     1999-08-08          MEKNES   27
33  34        QATAOUI               AYA     2004-01-23             FES   22
34  35       RAJOUANI            FAYSAL     2001-01-01           RABAT   25
35  36          RAKTA           NISRINE     2002-02-28          MEKNES   24
36  37          ZAHIR          MOHAMMED     1998-05-16             FES   28

In [132]:
df["Date_Naissance"] = pd.to_datetime(df["Date_Naissance"], format='%d/%m/%Y')

today = datetime.today()

#apply a function toi each colonne (axis=0)
df["Age"] = df["Date_Naissance"].apply(
    lambda x: today.year - x.year - ((today.month, today.day) < (x.month, x.day))
)

In [133]:
df

,N,Nom,Prenom,Date_Naissance,Ville_Naissance,age,Age
0,1,AIT EL FATMI,YOUSSEF,2000-09-03,FES,26,25
1,2,AJJAL,ISMAIL,2003-12-08,RABAT,23,22
2,3,AMILA,AYMANE,1994-06-28,FES,32,31
3,4,AZOUGH,YAHYA,2002-11-25,TANGER,24,23
4,5,BAH,MAMADOU OURY,2003-10-19,DAKHLA,23,22
5,6,BAYAD,OTMAN,1999-08-08,MEKNES,27,26
6,7,BOUSBAA,KENZA,2004-01-23,FES,22,22
7,8,BRIKA,SALMA,2001-01-01,RABAT,25,25
8,9,CHIAHNI,MAROUANE,2002-02-28,MEKNES,24,24
9,10,DELICIEUX,CALEB,1998-05-16,FES,28,27
10,11,ECHIBI,RAJAE,1992-02-29,FES,34,34
11,12,EL BASSRI,YASSINE,1995-10-08,NADOR,31,30
13,14,EL BOURAKADI,KHADIJA,2002-11-25,TANGER,24,23
14,15,EL FELLAK,HAJAR,2003-12-08,RABAT,23,22
15,16,EL HADRI,AYA,2002-02-28,MEKNES,24,24
16,17,EL HANSALI,HAFSSA,2004-01-23,FES,22,22
17,18,EL MOQADEM,AYMANE MOUBARIK,1994-06-28,FES,32,31
18,19,EL MOUHADDANA,YASSINE,1999-08-08,MEKNES,27,26
19,20,EL-MAKHLOUFI,MOHAMMED,2001-01-01,RABAT,25,25
21,22,ET-TAALABI,SEFIANE,1992-02-29,RABAT,34,34
23,24,GUARTET,ABDESSLAM,1994-06-28,FES,32,31
25,26,JAAFARI,NASRELLAH,1999-08-08,MEKNES,27,26
26,27,MAACHI,ABDELLAH,2002-11-25,TANGER,24,23
27,28,MELIANI,ROMAISSA,2000-09-03,FES,26,25
28,29,MEYABA,MOHAMED VALL,2003-08-12,RABAT,23,22
29,30,MIME,SAAD,1994-06-28,FES,32,31
30,31,NDIAYE,MOUHAMED NAZIROU,2002-11-25,TANGER,24,23
31,32,N'MAR,HAJAR,2003-10-19,DAKHLA,23,22
32,33,OUHCHOUCH,ZAKARIA,1999-08-08,MEKNES,27,26
33,34,QATAOUI,AYA,2004-01-23,FES,22,22
34,35,RAJOUANI,FAYSAL,2001-01-01,RABAT,25,25
35,36,RAKTA,NISRINE,2002-02-28,MEKNES,24,24
36,37,ZAHIR,MOHAMMED,1998-05-16,FES,28,27

In [139]:
df.drop('age', axis=1,inplace=True)

In [140]:
df.shape

(33, 6)

In [142]:
df

     N            Nom            Prenom Date_Naissance Ville_Naissance  Age
0    1   AIT EL FATMI           YOUSSEF     2000-09-03             FES   25
1    2          AJJAL            ISMAIL     2003-12-08           RABAT   22
2    3          AMILA            AYMANE     1994-06-28             FES   31
3    4         AZOUGH             YAHYA     2002-11-25          TANGER   23
4    5            BAH      MAMADOU OURY     2003-10-19          DAKHLA   22
5    6          BAYAD             OTMAN     1999-08-08          MEKNES   26
6    7        BOUSBAA             KENZA     2004-01-23             FES   22
7    8          BRIKA             SALMA     2001-01-01           RABAT   25
8    9        CHIAHNI          MAROUANE     2002-02-28          MEKNES   24
9   10      DELICIEUX             CALEB     1998-05-16             FES   27
10  11         ECHIBI             RAJAE     1992-02-29             FES   34
11  12      EL BASSRI           YASSINE     1995-10-08           NADOR   30
13  14   EL BOURAKADI           KHADIJA     2002-11-25          TANGER   23
14  15      EL FELLAK             HAJAR     2003-12-08           RABAT   22
15  16       EL HADRI               AYA     2002-02-28          MEKNES   24
16  17     EL HANSALI            HAFSSA     2004-01-23             FES   22
17  18     EL MOQADEM   AYMANE MOUBARIK     1994-06-28             FES   31
18  19  EL MOUHADDANA           YASSINE     1999-08-08          MEKNES   26
19  20   EL-MAKHLOUFI          MOHAMMED     2001-01-01           RABAT   25
21  22     ET-TAALABI           SEFIANE     1992-02-29           RABAT   34
23  24        GUARTET         ABDESSLAM     1994-06-28             FES   31
25  26        JAAFARI         NASRELLAH     1999-08-08          MEKNES   26
26  27         MAACHI          ABDELLAH     2002-11-25          TANGER   23
27  28        MELIANI          ROMAISSA     2000-09-03             FES   25
28  29         MEYABA      MOHAMED VALL     2003-08-12           RABAT   22
29  30           MIME              SAAD     1994-06-28             FES   31
30  31         NDIAYE  MOUHAMED NAZIROU     2002-11-25          TANGER   23
31  32          N'MAR             HAJAR     2003-10-19          DAKHLA   22
32  33      OUHCHOUCH           ZAKARIA     1999-08-08          MEKNES   26
33  34        QATAOUI               AYA     2004-01-23             FES   22
34  35       RAJOUANI            FAYSAL     2001-01-01           RABAT   25
35  36          RAKTA           NISRINE     2002-02-28          MEKNES   24
36  37          ZAHIR          MOHAMMED     1998-05-16             FES   27

6.	Ajouter une colonne "Email" : créer une adresse sous la forme prenom.nom@usmba.ac.ma à partir des colonnes Nom et Prénom en supprimant les espaces, apostrophes (') et tirets (-), puis en concaténant Nom et Prénom avec un point, en majuscules, et en ajoutant @usmba.ac.ma (ex : EL MOQADEM + AYMANE MOUBARIK → elmoqadem.aymanemoubarik@usmba.ac.ma, N'MAR + HAJAR → nmar.hajar@usmba.ac.ma, ET-TAALABI + SEFIANE → ettaalabi.sefiane@usmba.ac.ma).

In [145]:
def nettoyer(text):
    text = str(text).lower()
    text = text.replace(" ","").replace("'","").replace("-","")

    return text

df["Email"] = df["Nom"].apply(nettoyer)+"."+df["Prenom"].apply(nettoyer)+"@usmba.ac.ma"

In [147]:
df

,N,Nom,Prenom,Date_Naissance,Ville_Naissance,Age,Email
0,1,AIT EL FATMI,YOUSSEF,2000-09-03,FES,25,aitelfatmi.youssef@usmba.ac.ma
1,2,AJJAL,ISMAIL,2003-12-08,RABAT,22,ajjal.ismail@usmba.ac.ma
2,3,AMILA,AYMANE,1994-06-28,FES,31,amila.aymane@usmba.ac.ma
3,4,AZOUGH,YAHYA,2002-11-25,TANGER,23,azough.yahya@usmba.ac.ma
4,5,BAH,MAMADOU OURY,2003-10-19,DAKHLA,22,bah.mamadououry@usmba.ac.ma
5,6,BAYAD,OTMAN,1999-08-08,MEKNES,26,bayad.otman@usmba.ac.ma
6,7,BOUSBAA,KENZA,2004-01-23,FES,22,bousbaa.kenza@usmba.ac.ma
7,8,BRIKA,SALMA,2001-01-01,RABAT,25,brika.salma@usmba.ac.ma
8,9,CHIAHNI,MAROUANE,2002-02-28,MEKNES,24,chiahni.marouane@usmba.ac.ma
9,10,DELICIEUX,CALEB,1998-05-16,FES,27,delicieux.caleb@usmba.ac.ma
10,11,ECHIBI,RAJAE,1992-02-29,FES,34,echibi.rajae@usmba.ac.ma
11,12,EL BASSRI,YASSINE,1995-10-08,NADOR,30,elbassri.yassine@usmba.ac.ma
13,14,EL BOURAKADI,KHADIJA,2002-11-25,TANGER,23,elbourakadi.khadija@usmba.ac.ma
14,15,EL FELLAK,HAJAR,2003-12-08,RABAT,22,elfellak.hajar@usmba.ac.ma
15,16,EL HADRI,AYA,2002-02-28,MEKNES,24,elhadri.aya@usmba.ac.ma
16,17,EL HANSALI,HAFSSA,2004-01-23,FES,22,elhansali.hafssa@usmba.ac.ma
17,18,EL MOQADEM,AYMANE MOUBARIK,1994-06-28,FES,31,elmoqadem.aymanemoubarik@usmba.ac.ma
18,19,EL MOUHADDANA,YASSINE,1999-08-08,MEKNES,26,elmouhaddana.yassine@usmba.ac.ma
19,20,EL-MAKHLOUFI,MOHAMMED,2001-01-01,RABAT,25,elmakhloufi.mohammed@usmba.ac.ma
21,22,ET-TAALABI,SEFIANE,1992-02-29,RABAT,34,ettaalabi.sefiane@usmba.ac.ma
23,24,GUARTET,ABDESSLAM,1994-06-28,FES,31,guartet.abdesslam@usmba.ac.ma
25,26,JAAFARI,NASRELLAH,1999-08-08,MEKNES,26,jaafari.nasrellah@usmba.ac.ma
26,27,MAACHI,ABDELLAH,2002-11-25,TANGER,23,maachi.abdellah@usmba.ac.ma
27,28,MELIANI,ROMAISSA,2000-09-03,FES,25,meliani.romaissa@usmba.ac.ma
28,29,MEYABA,MOHAMED VALL,2003-08-12,RABAT,22,meyaba.mohamedvall@usmba.ac.ma
29,30,MIME,SAAD,1994-06-28,FES,31,mime.saad@usmba.ac.ma
30,31,NDIAYE,MOUHAMED NAZIROU,2002-11-25,TANGER,23,ndiaye.mouhamednazirou@usmba.ac.ma
31,32,N'MAR,HAJAR,2003-10-19,DAKHLA,22,nmar.hajar@usmba.ac.ma
32,33,OUHCHOUCH,ZAKARIA,1999-08-08,MEKNES,26,ouhchouch.zakaria@usmba.ac.ma
33,34,QATAOUI,AYA,2004-01-23,FES,22,qataoui.aya@usmba.ac.ma
34,35,RAJOUANI,FAYSAL,2001-01-01,RABAT,25,rajouani.faysal@usmba.ac.ma
35,36,RAKTA,NISRINE,2002-02-28,MEKNES,24,rakta.nisrine@usmba.ac.ma
36,37,ZAHIR,MOHAMMED,1998-05-16,FES,27,zahir.mohammed@usmba.ac.ma

7.	Ajouter une nouvelle colonne nommée "Accepted" qui accepte deux valeurs, Yes ou No. Si l’âge de l’étudiant ne dépasse pas 24 ans et sa ville natale est FES ou MEKNES, alors sa candidature pour avoir une bourse d’étude de master est acceptée, sinon, elle est refusée.

In [163]:
def acceptation(etd):
    if (etd["Age"] <= 24) & ((etd["Ville_Naissance"]=="FES") |  (etd["Ville_Naissance"]=="MEKNES")):
        return "YES"
    else:
        return "NO"

df["Accepted"]= df[["Age","Ville_Naissance"]].apply(acceptation, axis=1)

#def check_accept(row):
#    if row["Age"] <= 24 and row["Ville"].upper() in ["FES", "MEKNES"]:
#        return "Yes"
#    else:
#        return "No"

#df["Accepted"] = df.apply(check_accept, axis=1)

In [164]:
df

,N,Nom,Prenom,Date_Naissance,Ville_Naissance,Age,Email,Accepted
0,1,AIT EL FATMI,YOUSSEF,2000-09-03,FES,25,aitelfatmi.youssef@usmba.ac.ma,NO
1,2,AJJAL,ISMAIL,2003-12-08,RABAT,22,ajjal.ismail@usmba.ac.ma,NO
2,3,AMILA,AYMANE,1994-06-28,FES,31,amila.aymane@usmba.ac.ma,NO
3,4,AZOUGH,YAHYA,2002-11-25,TANGER,23,azough.yahya@usmba.ac.ma,NO
4,5,BAH,MAMADOU OURY,2003-10-19,DAKHLA,22,bah.mamadououry@usmba.ac.ma,NO
5,6,BAYAD,OTMAN,1999-08-08,MEKNES,26,bayad.otman@usmba.ac.ma,NO
6,7,BOUSBAA,KENZA,2004-01-23,FES,22,bousbaa.kenza@usmba.ac.ma,YES
7,8,BRIKA,SALMA,2001-01-01,RABAT,25,brika.salma@usmba.ac.ma,NO
8,9,CHIAHNI,MAROUANE,2002-02-28,MEKNES,24,chiahni.marouane@usmba.ac.ma,YES
9,10,DELICIEUX,CALEB,1998-05-16,FES,27,delicieux.caleb@usmba.ac.ma,NO
10,11,ECHIBI,RAJAE,1992-02-29,FES,34,echibi.rajae@usmba.ac.ma,NO
11,12,EL BASSRI,YASSINE,1995-10-08,NADOR,30,elbassri.yassine@usmba.ac.ma,NO
13,14,EL BOURAKADI,KHADIJA,2002-11-25,TANGER,23,elbourakadi.khadija@usmba.ac.ma,NO
14,15,EL FELLAK,HAJAR,2003-12-08,RABAT,22,elfellak.hajar@usmba.ac.ma,NO
15,16,EL HADRI,AYA,2002-02-28,MEKNES,24,elhadri.aya@usmba.ac.ma,YES
16,17,EL HANSALI,HAFSSA,2004-01-23,FES,22,elhansali.hafssa@usmba.ac.ma,YES
17,18,EL MOQADEM,AYMANE MOUBARIK,1994-06-28,FES,31,elmoqadem.aymanemoubarik@usmba.ac.ma,NO
18,19,EL MOUHADDANA,YASSINE,1999-08-08,MEKNES,26,elmouhaddana.yassine@usmba.ac.ma,NO
19,20,EL-MAKHLOUFI,MOHAMMED,2001-01-01,RABAT,25,elmakhloufi.mohammed@usmba.ac.ma,NO
21,22,ET-TAALABI,SEFIANE,1992-02-29,RABAT,34,ettaalabi.sefiane@usmba.ac.ma,NO
23,24,GUARTET,ABDESSLAM,1994-06-28,FES,31,guartet.abdesslam@usmba.ac.ma,NO
25,26,JAAFARI,NASRELLAH,1999-08-08,MEKNES,26,jaafari.nasrellah@usmba.ac.ma,NO
26,27,MAACHI,ABDELLAH,2002-11-25,TANGER,23,maachi.abdellah@usmba.ac.ma,NO
27,28,MELIANI,ROMAISSA,2000-09-03,FES,25,meliani.romaissa@usmba.ac.ma,NO
28,29,MEYABA,MOHAMED VALL,2003-08-12,RABAT,22,meyaba.mohamedvall@usmba.ac.ma,NO
29,30,MIME,SAAD,1994-06-28,FES,31,mime.saad@usmba.ac.ma,NO
30,31,NDIAYE,MOUHAMED NAZIROU,2002-11-25,TANGER,23,ndiaye.mouhamednazirou@usmba.ac.ma,NO
31,32,N'MAR,HAJAR,2003-10-19,DAKHLA,22,nmar.hajar@usmba.ac.ma,NO
32,33,OUHCHOUCH,ZAKARIA,1999-08-08,MEKNES,26,ouhchouch.zakaria@usmba.ac.ma,NO
33,34,QATAOUI,AYA,2004-01-23,FES,22,qataoui.aya@usmba.ac.ma,YES
34,35,RAJOUANI,FAYSAL,2001-01-01,RABAT,25,rajouani.faysal@usmba.ac.ma,NO
35,36,RAKTA,NISRINE,2002-02-28,MEKNES,24,rakta.nisrine@usmba.ac.ma,YES
36,37,ZAHIR,MOHAMMED,1998-05-16,FES,27,zahir.mohammed@usmba.ac.ma,NO

8.	Sauvegarder le résultat en utilisant pandas.DataFrame.to_csv.

In [165]:
df.to_csv(r"C:\Users\hp\Desktop\MASTER_1\S2\PBI_other\PBI\MLAIM_cleaned.csv", index=False)